# Generated by Django 5.0.4 on 2024-04-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=256, null=True)),
                ('user_wallet', models.DecimalField(decimal_places=3, max_digits=18)),
            ],
        ),
    ]
