# Generated by Django 5.0.4 on 2024-08-21 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('admin_name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('acc_panels', models.BooleanField(default=False)),
                ('acc_products', models.BooleanField(default=False)),
                ('acc_botmanagment', models.BooleanField(default=False)),
                ('acc_admins', models.BooleanField(default=False)),
                ('acc_users', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'v2_admins',
            },
        ),
        migrations.CreateModel(
            name='botsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_pay', models.SmallIntegerField(default=0)),
                ('kartbkart_pay', models.SmallIntegerField(default=0)),
                ('forcechjoin', models.SmallIntegerField(default=0)),
                ('moneyusrtousr', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'v2_botsettings',
            },
        ),
        migrations.CreateModel(
            name='channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=56)),
                ('channel_url', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_id', models.BigIntegerField(blank=True, null=True)),
                ('ch_status', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'v2_channels',
            },
        ),
        migrations.CreateModel(
            name='inovices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(blank=True, max_length=56, null=True)),
                ('panel_name', models.CharField(max_length=56)),
                ('product_name', models.CharField(max_length=56)),
                ('data_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expire_date', models.SmallIntegerField()),
                ('pro_cost', models.BigIntegerField()),
                ('gift_code', models.CharField(blank=True, max_length=56, null=True)),
                ('discount', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('paid_status', models.PositiveBigIntegerField(default=0)),
                ('paid_mode', models.CharField(choices=[('wlt', 'wallet'), ('kbk', 'kart-be-kart'), ('arz', 'arz-digital')], max_length=3)),
                ('config_name', models.CharField(blank=True, max_length=56, null=True)),
                ('kind_pay', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'v2_inovices',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.SmallIntegerField(default=1)),
                ('product_name', models.CharField(max_length=128)),
                ('data_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expire_date', models.SmallIntegerField()),
                ('pro_cost', models.BigIntegerField()),
                ('panel_id', models.SmallIntegerField(blank=True, null=True)),
                ('categori_id', models.SmallIntegerField(blank=True, null=True)),
                ('pro_id_str', models.CharField(blank=True, max_length=36, null=True)),
                ('sort_id', models.SmallIntegerField(blank=True, null=True)),
                ('inbounds_selected', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'v2_products',
            },
        ),
        migrations.CreateModel(
            name='shomarekart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=56, null=True)),
                ('ownername', models.CharField(blank=True, max_length=124, null=True)),
                ('bank_card', models.BigIntegerField(blank=True, null=True)),
                ('bank_status', models.SmallIntegerField(default=1)),
                ('bank_inmsg', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'v2_shomarekart',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=256, null=True)),
                ('user_wallet', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'v2_users',
            },
        ),
        migrations.CreateModel(
            name='v2panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_status', models.SmallIntegerField(default=1)),
                ('panel_name', models.CharField(max_length=256)),
                ('panel_url', models.CharField(max_length=256)),
                ('panel_username', models.CharField(max_length=256)),
                ('panel_password', models.CharField(max_length=256)),
                ('panel_id_str', models.CharField(blank=True, max_length=36, null=True)),
                ('reality_flow', models.CharField(max_length=256, null=True)),
                ('capcity_mode', models.PositiveSmallIntegerField(default=2)),
                ('all_capcity', models.BigIntegerField(blank=True, default=0, null=True)),
                ('sold_capcity', models.BigIntegerField(blank=True, default=0, null=True)),
                ('panel_sale_mode', models.PositiveSmallIntegerField(default=1)),
                ('send_links_mode', models.PositiveSmallIntegerField(default=0)),
                ('send_qrcode_mode', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'v2_v2panel',
            },
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('decline_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('payment_stauts', models.CharField(blank=True, max_length=56, null=True)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('inovice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.inovices')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.users', to_field='user_id')),
            ],
            options={
                'db_table': 'v2_payments',
            },
        ),
        migrations.AddField(
            model_name='inovices',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.users', to_field='user_id'),
        ),
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_subscription', models.CharField(max_length=56)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.users', to_field='user_id')),
                ('panel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.v2panel')),
            ],
            options={
                'db_table': 'v2_subscriptions',
            },
        ),
    ]
