# Generated by Django 5.0.4 on 2024-04-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_wallet',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
    ]
