# Generated by Django 5.0.4 on 2024-09-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_stauts',
            new_name='payment_status',
        ),
    ]
