# Generated by Django 5.0.4 on 2024-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0002_alter_users_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_wallet',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
    ]
