# Generated by Django 5.0.4 on 2024-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0002_rename_payment_stauts_payments_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='acc_staticts',
            field=models.BooleanField(default=False),
        ),
    ]
