# Generated by Django 5.0.4 on 2024-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0003_admins_acc_staticts'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='ch_usage',
            field=models.CharField(blank=True, choices=[('logc', 'logs_channel'), ('fjch', 'force_join_channel')], max_length=4, null=True),
        ),
    ]
