# Generated by Django 5.0.4 on 2024-09-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0004_channels_ch_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='buyservice_notf',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='moneyusrtousr_notf',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='newusers_notf',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='tamdidservice_notf',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='walletcharge_notf',
            field=models.SmallIntegerField(default=0),
        ),
    ]
