# Generated by Django 5.0.4 on 2024-04-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0004_alter_users_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('is_admin', models.BooleanField(default='False')),
                ('is_owner', models.BooleanField(default='False')),
            ],
        ),
    ]
