# Generated by Django 5.0.4 on 2024-04-10 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0007_rename_admin_admins_alter_admins_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainrobot.users'),
        ),
    ]
