# Generated by Django 5.0.4 on 2024-04-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0008_alter_admins_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='mainrobot.users'),
        ),
    ]
