# Generated by Django 5.0.4 on 2024-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0010_alter_admins_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=256)),
                ('data_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expire_date', models.SmallIntegerField()),
                ('pro_cost', models.BigIntegerField()),
                ('panel_id', models.SmallIntegerField()),
                ('categori_id', models.SmallIntegerField()),
                ('pro_id', models.SmallIntegerField()),
                ('sort_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='v2panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=256)),
                ('panel_url', models.CharField(max_length=256)),
                ('panel_user', models.CharField(max_length=256)),
                ('panel_password', models.CharField(max_length=256)),
                ('reality_flow', models.CharField(max_length=256)),
                ('capcity', models.BigIntegerField()),
            ],
            options={
                'db_table': 'TeleBot_v2panel',
            },
        ),
    ]
