# Generated by Django 5.0.4 on 2024-04-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0011_products_v2panel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='TeleBot_products',
        ),
    ]
