# Generated by Django 5.0.4 on 2024-04-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0012_alter_products_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='v2panel',
            old_name='panel_user',
            new_name='panel_username',
        ),
    ]
