# Generated by Django 5.0.4 on 2024-04-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0018_remove_v2panel_panel_id_v2panel_panel_id_str_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='pro_id',
            new_name='pro_id_str',
        ),
    ]
