# Generated by Django 5.0.4 on 2024-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0019_rename_pro_id_products_pro_id_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='v2panel',
            name='panel_status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
