# Generated by Django 5.0.4 on 2024-04-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0020_v2panel_panel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v2panel',
            name='reality_flow',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
