# Generated by Django 5.0.4 on 2024-05-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0023_rename_soled_capcity_v2panel_sold_capcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v2panel',
            name='all_capcity',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='v2panel',
            name='sold_capcity',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
