# Generated by Django 5.0.4 on 2024-05-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0024_alter_v2panel_all_capcity_alter_v2panel_sold_capcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=128),
        ),
    ]
