# Generated by Django 5.0.4 on 2024-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0025_alter_products_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='inovices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_username', models.CharField(blank=True, max_length=56, null=True)),
                ('panel_name', models.CharField(max_length=56)),
                ('product_name', models.CharField(max_length=56)),
                ('data_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expire_date', models.SmallIntegerField()),
                ('pro_cost', models.BigIntegerField()),
                ('gift_code', models.CharField(max_length=56)),
                ('discount', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('paid_status', models.PositiveBigIntegerField(default=0)),
                ('paid_mode', models.CharField(choices=[('wlt', 'wallet'), ('kbk', 'kart-be-kart'), ('arz', 'arz-digital')], max_length=3)),
            ],
            options={
                'db_table': 'TeleBot_inovices',
            },
        ),
    ]
