# Generated by Django 5.0.4 on 2024-05-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0026_inovices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inovices',
            name='gift_code',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='v2panel',
            name='capcity_mode',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
