# Generated by Django 5.0.4 on 2024-05-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0028_alter_inovices_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inovices',
            name='config_name',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
