# Generated by Django 5.0.4 on 2024-06-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0029_inovices_config_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('decline_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('payment_stauts', models.CharField(blank=True, max_length=56, null=True)),
                ('inovice_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.users')),
            ],
            options={
                'db_table': 'Telebot_paments',
            },
        ),
    ]
