# Generated by Django 5.0.4 on 2024-06-07 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0030_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.users', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
