# Generated by Django 5.0.4 on 2024-06-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0031_alter_payments_user_id_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inovices',
            table='TeleBot_payments',
        ),
        migrations.AlterModelTable(
            name='payments',
            table=None,
        ),
    ]
