# Generated by Django 5.0.4 on 2024-06-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0032_alter_inovices_table_alter_payments_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inovices',
            table='TeleBot_inovices',
        ),
        migrations.AlterModelTable(
            name='payments',
            table='TeleBot_payments',
        ),
    ]
