# Generated by Django 5.0.4 on 2024-06-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0036_alter_inovices_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='inovice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainrobot.inovices'),
        ),
    ]
