# Generated by Django 5.0.4 on 2024-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0037_alter_payments_inovice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=56)),
                ('channel_url', models.CharField(blank=True, max_length=256, null=True)),
                ('channel_id', models.SmallIntegerField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
