# Generated by Django 5.0.4 on 2024-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0038_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.IntegerField(blank=True, max_length=32, null=True),
        ),
    ]
