# Generated by Django 5.0.4 on 2024-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0039_alter_channels_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.BigIntegerField(blank=True, max_length=32, null=True),
        ),
    ]
