# Generated by Django 5.0.4 on 2024-06-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0040_alter_channels_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
