# Generated by Django 5.0.4 on 2024-06-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0041_alter_channels_channel_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channels',
            table='TeleBot_channels',
        ),
    ]
