# Generated by Django 5.0.4 on 2024-06-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0043_v2panel_inbounds_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='panel_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
