# Generated by Django 5.0.4 on 2024-07-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0045_remove_v2panel_inbounds_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
