# Generated by Django 5.0.4 on 2024-07-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0046_products_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=56, null=True)),
                ('bank_kard', models.BigIntegerField(blank=True, null=True)),
                ('bank_status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'TeleBot_paymentsetting',
            },
        ),
    ]
