# Generated by Django 5.0.4 on 2024-07-16 00:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0051_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
