# Generated by Django 5.0.4 on 2024-07-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0052_subscriptions_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='inovices',
            name='kind_pay',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
