# Generated by Django 5.0.4 on 2024-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainrobot', '0054_admins_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='admin_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
